# 物件導向入門

In [1]:
class Student: #類別
    pass

st1 = Student()#物件
print(st1)


In [4]:
class Student: #類別
    pass
st1 = Student()
st2 = Student()
# 建立屬性
st1.height = 180
st1.weight = 75

print(st1.height)
print(st1.weight)


print(st2.height)#因為沒有st2.height = 0
print(st2.weight)


180
75


AttributeError: 'Student' object has no attribute 'height'

In [6]:
class Student: #類別
    def __init__(self,name,height = 100,weight = 10):#可以設定屬性
        self.name = name
        self.height = height
        self.weight = weight
st1 = Student("Ken")
print(st1.name,st1.height,st1.weight)
st2 = Student("Vivin",165,48)
print(st2.name,st2.height,st2.weight)

Ken 100 10
Vivin 165 48


In [10]:
class Student: #類別
    def __init__(self,name,height = 100,weight = 10):#可以設定屬性
        self.name = name
        self.height = height
        self.weight = weight
    def printInfo(self): #自定義的函數
        print(self.name,self.height,self.weight)
        
st1 = Student("Joy",155,40)        
st1.printInfo()
st2 = Student("Lucy",165,52)
st2.printInfo()

Joy 155 40
Lucy 165 52


## 寫入檔案

In [11]:
text = """python與中文AAA
1. 我們來試試看中文儲存能力。
2. 許這個字會有編碼衝突風險。
3. 犇這個字必須是utf8編碼才有。
"""
print(text,file=open('data.txt','w',encoding='utf-8'))

## 讀取

In [12]:
file = open("data.txt",'r',encoding='utf-8')
txt = file.read()
print(txt)

python與中文AAA
1. 我們來試試看中文儲存能力。
2. 許這個字會有編碼衝突風險。
3. 犇這個字必須是utf8編碼才有。




### JSON

In [17]:
import json
jsonStr = '{"python":"good","score":100,"class":true}'
json2 = json.dumps(jsonStr,ensure_ascii=False) #把物件轉成str
print(type(json2))
print(json2)
json3 = json.loads(jsonStr)#重點Json格式的字串轉成字典
print(type(json3))
print(json3["score"])
print(json3)

<class 'str'>
"{\"python\":\"good\",\"score\":100,\"class\":true}"
<class 'dict'>
100
{'python': 'good', 'score': 100, 'class': True}


# Python 程式偵錯

+ Syntax Errors 語法錯誤
 + 該行語法錯誤，Python 無法編譯執行。
 + 修正語法錯誤
+ Exception 例外
 + 語法撰寫上沒有錯誤，執行時因資料邏輯或外部系統狀態發生錯誤， Python 會引發例外(Exception) 
 + 如果例外沒有被處理而傳遞到Python直譯器，程式中斷執行

In [32]:
num1 = 10
num2 = 2

try:
    print(num1 / num2)
except:    #如果有錯誤會執行這個區塊
    print("分母不可為0")

5.0


## Numpy
+ 可做到的功能
  + 快速的多維陣列操作。
  + 可靠的科學功能函數庫。
  + 可協助繪圖工具進行繪圖。
+ NumPy 是幾乎每個科學 Python 應用程序或模組的核心，它提供了以向量化形式的快速 N-d 陣列類型可供操作。

In [37]:
import numpy as np 
a = np.array([1,3,5,7,9])
b = np.array([3,5,6,7,9])
c = a + b
print(c)
c = a - b
print(c)
c = a * b
print(c)
c = a / b
print(c)

[ 4  8 11 14 18]
[-2 -2 -1  0  0]
[ 3 15 30 49 81]
[0.33333333 0.6        0.83333333 1.         1.        ]


## 陣列附加資料

In [39]:
import numpy as np 
a = np.array([1,3,5,7,9])
b = np.append(a,[10,11,12])
print(b)

[ 1  3  5  7  9 10 11 12]


## 陣列插入資料

In [40]:
import numpy as np 
a = np.array([1,3,5,7,9])
b = np.insert(a,2,[11,18])
print(b)

[ 1  3 11 18  5  7  9]


## 陣列刪除資料

In [41]:
import numpy as np 
a = np.array([1,3,5,7,9])
b = np.delete(a,2) #填上要移除的index
print(b)

[1 3 7 9]


In [42]:
! pip install beautifulsoup4

In [43]:
! pip install html5lib

In [44]:
! pip install requests

In [45]:
! pip install openai